# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: alipio
email: kristine.alipio@gmail.com
description: THIS IS MY WEBSITE.  HOW COOL IS THAT.
baseurl: "" # the subpath of your site, e.g. /blog
url: "alip.io" # the base hostname & protocol for your site
twitter_username: kalipio
github_username:  kalipio

# Build settings
markdown: kramdown
